Document: sidux-art-kde
Title: Debian sidux-art-kde Manual
Author: <insert document author here>
Abstract: This manual describes what sidux-art-kde is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sidux-art-kde/sidux-art-kde.sgml.gz

Format: postscript
Files: /usr/share/doc/sidux-art-kde/sidux-art-kde.ps.gz

Format: text
Files: /usr/share/doc/sidux-art-kde/sidux-art-kde.text.gz

Format: HTML
Index: /usr/share/doc/sidux-art-kde/html/index.html
Files: /usr/share/doc/sidux-art-kde/html/*.html

  
